// react/App.jsx
import React, { useState } from 'react';
import './App.css';
import '../core/page-block-renderer';

const initialItems = [
  {
    type: "text",
    value: "hello, world!",
    editable: true
  },
  {
    type: "youtube",
    value: "https://www.youtube.com/embed/1EL6L2dh5pY",
    editable: true
  }
];

function App() {

  const [items, setItems] = useState(initialItems);

  const handleDragStart = (e, index) => {
    e.dataTransfer.setData('dragIndex', index);
  };

  const handleDrop = (e, dropIndex) => {
    const dragIndex = e.dataTransfer.getData('dragIndex');
    const newItems = [...items];
    const [draggedItem] = newItems.splice(dragIndex, 1);
    newItems.splice(dropIndex, 0, draggedItem);

    setItems(newItems);
  };

  const handleDragOver = (e) => {
    e.preventDefault();
  };

  return (
      <div className="App">
        <header className="App-header">
          <h1>WebComponents In React</h1>
        </header>
        <h2>Edit Mode</h2>
        <div className="App-list">
          {items.map((item, index) => (
              <page-block-renderer
                  key={item.id}
                  draggable
                  onDragStart={(e) => handleDragStart(e, index)}
                  onDragOver={(e) => handleDragOver(e)}
                  onDrop={(e) => handleDrop(e, index)}
                  data={JSON.stringify(item)}>
              </page-block-renderer>
          ))}
        </div>
      </div>
  );
}

export default App;

// vue/App.vue
<template>
  <div id="app">
    <header class="vue-header">
      <h1 class="vue-h1">WebComponents In Vue</h1>
    </header>
    <h2>Compact Mode</h2>
    <ul className="vue-list">
      <li v-for="item in items" class="draggable-item">
          <svg width="50" height="50" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <circle cx="5" cy="5" r="1" fill="#323741"/>
            <circle cx="10" cy="5" r="1" fill="#323741"/>
            <circle cx="5" cy="10" r="1" fill="#323741"/>
            <circle cx="10" cy="10" r="1" fill="#323741"/>
            <circle cx="5" cy="15" r="1" fill="#323741"/>
            <circle cx="10" cy="15" r="1" fill="#323741"/>
          </svg>
          <div class="compact-block">
            <page-block-renderer :data="item"></page-block-renderer>
          </div>
      </li>
    </ul>
  </div>
</template>

<script setup>
import { ref } from 'vue';

const items = ref([
  {
    type: "text",
    value: "hello, world!",
    editable: false,
    compact: true
  },
  {
    type: "youtube",
    value: "https://www.youtube.com/embed/1EL6L2dh5pY",
    editable: false,
    compact: true
  }
]);
</script>

<script>
export default {
  name: 'App',
}
</script>

<style>
template {
  background-color: #323741;
}

#app {
  text-align: center;
  height: 100vh;
  color: white;
  background-color: #22262c;
  overflow-y: auto;
}

.vue-header {
  display: flex;
  flex-direction: column;
  color: white;
  background-color: #25403f;
}

.vue-list {
  padding: 1em 0;
  list-style-type: none;
}

.draggable-item {
  display: flex;
  align-items: center;
  padding: 0;
  justify-content: flex-start;
}

.compact-block {
  width: 100%;
}

::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}

::-webkit-scrollbar-track {
  background: #f1f1f1;
}

::-webkit-scrollbar-thumb {
  background: #888;
  border-radius: 10px;
}

::-webkit-scrollbar-thumb:hover {
  background: #555;
}

::-webkit-scrollbar-corner {
  background: #999;
}
</style>
